Manuel83/craftbeerpi3

modules/base_plugins/gpio_actor/__init__.py
Closes https://github.com/Manuel83/craftbeerpi3/issues/7
=> Add GPIO Pin 27

modules/base_plugins/fermenter_hysteresis/__init__.py
=> Allow floats for offeset min/max

config/schema.sql
Allow the schema.sql file to be re-run if it changes, this will resolve the need to destroy the database afte the most recent changes.
=> Allow SQL file to be re-run

modules/base_plugins/one_wire/__init__.py
closes https://github.com/Manuel83/craftbeerpi3/issues/33
alternatively as a plugin: https://github.com/carlallen/cbpi_BiasedOneWireSensor
=> Allow specifying an offset on onewire sensor

modules/core/core.py, modules/notification/__init__.py
This will allow any plugin to listen for a notification and respond accordingly.
=> Change to notification to use message event bus

modules/core/core.py
=> Select properties configurable for steps

modules/base_plugins/fermenter_hysteresis/__init__.py
@torrdan  noticed an issue with the descriptions in #65 this resolves the issue
=> Improved descriptions for fermenter hysteresis

modules/base_plugins/brew_steps/__init__.py
Changes int() on mashin and boilsteps to a float() value to check if the Target Temp is reached.  This allows decimals value to not error out in the log.
=> Update all brew steps to allow decimal values

run.py, update/3_port_config.sql
As part of discussion in user group. It's useful to be able to run the server on a different port.
=> Allow setting port by param

modules/base_plugins/brew_steps/__init__.py
Adds beeps and a text notification at the end of a mash step.
=> Add notification(s) at the end of mashstep and boilstep

modules/core/controller.py, modules/logs/endpoints.py
I have implemented code in my plugin that I want to appear in the fermenter chart, this modification allows plugins to change the output of charts on kettles and fermenters based on a staticmethod in the logic class.
My plugin changing the chart:
https://github.com/carlallen/cbpi_PIDFermentationChamber/blob/master/__init__.py#L10
=> Allow modifying chart data in plugins

modules/core/core.py
=> Default value for Property.Number

modules/core/props.py
=> Set default value for TextProperty to fix bug

modules/core/core.py, requirements.txt
This will allow setting the port in the parameters section in 3.1
=> Restore port config for 3.1

modules/base_plugins/brew_steps/__init__.py, modules/recipe_import/beerxml.py
Reverts Manuel83/craftbeerpi3#105
=> Revert "Updates the boilstep and beerxml recipe import"

config/schema.sql, modules/buzzer/__init__.py
Adding Buzzer Beep Level because some Buzzers are triggered by 0V for making sound
=> Buzzer Beep Level

install.sh
Added a coose for a combination of CraftBeerPi Stop, (6), del all log files (9) and CraftBeerPi Start(5).
This one makes it more easy to test plugins or to test new parameters
=> Added a combinaton of stop-del logfiles-start

modules/base_plugins/hysteresis/__init__.py
removed lines 37 and 38 to make hysteresis work properly.  closes #180
=> Fix hysteresis turning off heater

modules/core/core.py
I was reading over core to familiarize myself with CP3 and found this duplicate line.
=> Remove duplicate line

modules/recipe_import/beerxml.py
The BeerXML import works great! However, the hop additions were not imported... By reading the HOP elements from BeerXML, these additions can be retained.
This does not import the boil-time additions which may be present in MISC elements. Maybe I'll get to implementing these some other time.
Please provide any feedback you might have, Python is not my native language so I might be lacking some Python zen.
=> Import hop alerts from BeerXML

Dockerfile, README.md, docker-compose.yml
This uses the official python docker images to allow you to ease development of CraftbeerPi3 and its plugins without having to code on a raspberry pi or install any requirements onto your host machine.
=> Docker files for ease of development on PCs/macs
